import type { Category, Product } from "./types";

export const categories: Category[] = [
  { name: "UPS Systems", slug: "ups-systems", description: "Line interactive, online & industrial UPS for every load." },
  { name: "Inverters & Batteries", slug: "inverters-batteries", description: "Home inverters, tubular & SMF batteries from trusted brands." },
  { name: "Stabilizers & Transformers", slug: "stabilizers-transformers", description: "1-Phase & 3-Phase stabilizers, isolation transformers, OVCD." },
  { name: "Electrical Panels", slug: "electrical-panels", description: "APFC panels, PLC systems, retrofication and panel building." },
  { name: "Solar Systems", slug: "solar-systems", description: "On-grid & off-grid solar with net-metering support." },
  { name: "Networking", slug: "networking", description: "Routers, switches and power distribution units." },
  { name: "Meters & Monitoring", slug: "meters-monitoring", description: "Multifunction meters, MSEDCL approved energy meters & sub-meters." },
  { name: "Lighting & Wiring", slug: "lighting-wiring", description: "Street lights, highmast and home wiring material at discount." },
  { name: "Testing Equipment", slug: "testing-equipment", description: "Insulation testers, earth testers, megohmmeters and load test kits." },
  { name: "Measuring Instruments", slug: "measuring-instruments", description: "Multimeters, clamp meters, calibrators and oscilloscopes for site & lab." },
  { name: "Electrical", slug: "electrical", description: "Switches, MCBs, RCCBs, contactors, relays and general electrical accessories." },
  { name: "Power Tools", slug: "power-tools", description: "Drills, grinders, impact drivers and corded/cordless power tools for industrial use." },
  { name: "Hand Tools", slug: "hand-tools", description: "Pliers, screwdrivers, wrench sets, cable cutters and electrician hand tools." },
];

const img = (q: string) => `https://images.unsplash.com/${q}?auto=format&fit=crop&w=1000&q=80`;

export const products: Product[] = [
  {
    name: "APC Line Interactive UPS 1500VA",
    slug: "apc-line-interactive-ups-1500va",
    description: "Reliable battery back-up for desktops, routers and small office equipment. Auto voltage regulation and surge protection built-in.",
    category: "ups-systems",
    brand: "APC",
    price: 8499,
    mrp: 9990,
    stock: 25,
    images: [img("photo-1591488320449-011701bb6704")],
    specs: { Capacity: "1500VA / 865W", Topology: "Line Interactive", Outlets: "3 Battery + 3 Surge", Warranty: "2 Years" },
    featured: true,
  },
  {
    name: "APC Online UPS 3KVA 1-Phase",
    slug: "apc-online-ups-3kva",
    description: "True double-conversion online UPS for sensitive loads. Ideal for servers, medical and lab equipment.",
    category: "ups-systems",
    brand: "APC",
    price: 58999,
    mrp: 64500,
    stock: 8,
    images: [img("photo-1581092580497-e0d23cbdf1dc")],
    specs: { Capacity: "3KVA / 2700W", Topology: "Online Double Conversion", Input: "1-Phase", Warranty: "2 Years" },
    featured: true,
  },
  {
    name: "Eaton 9PX Industrial UPS 6KVA",
    slug: "eaton-9px-industrial-ups-6kva",
    description: "Industrial grade UPS with high efficiency and hot-swappable batteries. Suited for data centres and factories.",
    category: "ups-systems",
    brand: "Eaton",
    price: 145000,
    stock: 4,
    images: [img("photo-1558494949-ef010cbdcc31")],
    specs: { Capacity: "6KVA / 5400W", Efficiency: "95%", Form: "Tower / Rack", Warranty: "3 Years" },
  },
  {
    name: "Luminous Inverlast Tubular Battery 220Ah",
    slug: "luminous-inverlast-220ah",
    description: "Tall tubular battery with 60-month warranty. Perfect partner for home inverters of 1-2 KVA.",
    category: "inverters-batteries",
    brand: "Luminous",
    price: 18999,
    mrp: 22500,
    stock: 30,
    images: [img("photo-1620714223084-8fcacc6dfd8d")],
    specs: { Capacity: "220 Ah", Type: "Tall Tubular", Warranty: "60 Months" },
    featured: true,
  },
  {
    name: "Microtek Home Inverter 1100VA",
    slug: "microtek-home-inverter-1100va",
    description: "Pure sinewave inverter with intelli battery gravity controller for longer battery life.",
    category: "inverters-batteries",
    brand: "Microtek",
    price: 8990,
    stock: 20,
    images: [img("photo-1580906855215-0e1d4ba53254")],
    specs: { Capacity: "1100VA", Output: "Pure Sinewave", Warranty: "2 Years" },
  },
  {
    name: "Amaron Quanta SMF Battery 12V 100Ah",
    slug: "amaron-quanta-smf-12v-100ah",
    description: "Maintenance-free VRLA battery for UPS and telecom backup applications.",
    category: "inverters-batteries",
    brand: "Amaron",
    price: 9450,
    stock: 18,
    images: [img("photo-1593941707882-a5bba14938c7")],
    specs: { Voltage: "12V", Capacity: "100Ah", Type: "SMF VRLA" },
  },
  {
    name: "1-Phase Servo Stabilizer 5KVA",
    slug: "servo-stabilizer-5kva-1ph",
    description: "Servo-controlled voltage stabilizer with wide input range. Perfect for AC, refrigerators, home appliances.",
    category: "stabilizers-transformers",
    brand: "Shreem",
    price: 16500,
    stock: 12,
    images: [img("photo-1581092918056-0c4c3acd3789")],
    specs: { Capacity: "5KVA", Phase: "Single", InputRange: "150-280V", Warranty: "2 Years" },
  },
  {
    name: "3-Phase Isolation Transformer 10KVA",
    slug: "3ph-isolation-transformer-10kva",
    description: "Galvanic isolation transformer for sensitive industrial and medical equipment.",
    category: "stabilizers-transformers",
    brand: "Shreem",
    price: 38500,
    stock: 6,
    images: [img("photo-1565043589221-1a6fd9ae45c7")],
    specs: { Capacity: "10KVA", Phase: "3-Phase", Type: "K-Rated Isolation" },
  },
  {
    name: "OVCD 1-Phase Over Voltage Cut-out Device",
    slug: "ovcd-1ph",
    description: "Protects equipment from voltage surges. Auto cut-off and reset.",
    category: "stabilizers-transformers",
    brand: "Usha",
    price: 4200,
    stock: 14,
    images: [img("photo-1631710404550-49a5c1deaad5")],
    specs: { Phase: "Single", Rating: "16A", Reset: "Auto" },
  },
  {
    name: "APFC Panel 100 kVAr",
    slug: "apfc-panel-100kvar",
    description: "Automatic Power Factor Correction panel with EPCOS capacitors and L&T contactors. Custom-built to load.",
    category: "electrical-panels",
    brand: "L&T / EPCOS",
    price: 185000,
    stock: 3,
    images: [img("photo-1581094794329-c8112a89af12")],
    specs: { Rating: "100 kVAr", Steps: "8 Steps", Controller: "EPCOS BR6000" },
    featured: true,
  },
  {
    name: "PLC Control Panel — Mitsubishi FX5U",
    slug: "plc-panel-mitsubishi-fx5u",
    description: "Customisable PLC panel with HMI, suitable for process automation and machine control.",
    category: "electrical-panels",
    brand: "Mitsubishi",
    price: 95000,
    stock: 5,
    images: [img("photo-1597852074816-d933c7d2b988")],
    specs: { PLC: "Mitsubishi FX5U", HMI: "7\" Touch", IO: "Up to 32" },
  },
  {
    name: "Schneider Multifunction Meter EM6400",
    slug: "schneider-mfm-em6400",
    description: "Class 0.5 multifunction power & energy meter with Modbus output.",
    category: "meters-monitoring",
    brand: "Schneider",
    price: 14500,
    stock: 10,
    images: [img("photo-1620714223084-8fcacc6dfd8d")],
    specs: { Class: "0.5", Comms: "RS-485 Modbus", Display: "LED" },
  },
  {
    name: "MSEDCL Approved 3-Phase Energy Meter",
    slug: "msedcl-3ph-energy-meter",
    description: "MSEDCL approved 3-phase energy meter for sub-metering and billing.",
    category: "meters-monitoring",
    brand: "HPL",
    price: 6800,
    stock: 22,
    images: [img("photo-1581094794329-c8112a89af12")],
    specs: { Phase: "3-Phase", Approval: "MSEDCL", Class: "1.0" },
  },
  {
    name: "Off-Grid Solar System 3kW",
    slug: "off-grid-solar-3kw",
    description: "Complete 3kW off-grid solar package — panels, inverter, charge controller and batteries.",
    category: "solar-systems",
    brand: "Luminous",
    price: 215000,
    stock: 4,
    images: [img("photo-1509391366360-2e959784a276")],
    specs: { Capacity: "3kW", Panels: "Mono PERC", Battery: "150Ah x 4", Warranty: "5 Years (system)" },
    featured: true,
  },
  {
    name: "On-Grid Solar System 5kW with Net Meter",
    slug: "on-grid-solar-5kw",
    description: "Grid-tied solar with net-metering coordination for MSEDCL approvals.",
    category: "solar-systems",
    brand: "Delta",
    price: 320000,
    stock: 3,
    images: [img("photo-1509395176047-4a66953fd231")],
    specs: { Capacity: "5kW", Inverter: "Delta", NetMeter: "Included" },
  },
  {
    name: "D-Link 8-Port Unmanaged Switch",
    slug: "dlink-8-port-switch",
    description: "Plug-and-play gigabit unmanaged switch for offices and small networks.",
    category: "networking",
    brand: "D-Link",
    price: 1850,
    stock: 40,
    images: [img("photo-1544197150-b99a580bb7a8")],
    specs: { Ports: "8 x Gigabit", Type: "Unmanaged" },
  },
  {
    name: "D-Link AC1200 Wi-Fi Router",
    slug: "dlink-ac1200-router",
    description: "Dual-band AC1200 wireless router for homes and small businesses.",
    category: "networking",
    brand: "D-Link",
    price: 2399,
    stock: 28,
    images: [img("photo-1606904825846-647eb07f5be2")],
    specs: { WiFi: "AC1200 Dual Band", LAN: "4 x Gigabit" },
  },
  {
    name: "Rack-Mount Power Distribution Unit",
    slug: "rack-mount-pdu",
    description: "1U metered PDU with 8 IEC C13 outlets, 16A input.",
    category: "networking",
    brand: "APC",
    price: 12500,
    stock: 9,
    images: [img("photo-1558494949-ef010cbdcc31")],
    specs: { Form: "1U Rack", Outlets: "8 x IEC C13", Input: "16A" },
  },
  {
    name: "12.5 Mtr Highmast Lighting Pole",
    slug: "12-5m-highmast-pole",
    description: "Octagonal highmast pole with raise & lower system, suitable for grounds and chowks. Includes LED flood lights.",
    category: "lighting-wiring",
    brand: "Usha",
    price: 215000,
    stock: 2,
    images: [img("photo-1517472292914-9570a594783b")],
    specs: { Height: "12.5 metre", Type: "Octagonal", Lights: "4 x 150W LED" },
  },
  {
    name: "LED Street Light 90W",
    slug: "led-street-light-90w",
    description: "IP66 outdoor LED street light, ideal for roads and society lighting.",
    category: "lighting-wiring",
    brand: "Crompton Greaves",
    price: 4250,
    stock: 35,
    images: [img("photo-1497436072909-60f360e1d4b1")],
    specs: { Wattage: "90W", IP: "IP66", Lumens: "10,800 lm" },
  },
  {
    name: "Polycab 2.5 sq.mm House Wire (90m Coil)",
    slug: "polycab-2-5-sqmm-wire",
    description: "FR PVC insulated single-core copper wire — ISI marked.",
    category: "lighting-wiring",
    brand: "Polycab",
    price: 2850,
    mrp: 3500,
    stock: 60,
    images: [img("photo-1581092918056-0c4c3acd3789")],
    specs: { Size: "2.5 sq.mm", Length: "90m", Standard: "ISI / IS 694" },
  },
];

export const brands = [
  "APC", "Schneider Electric", "Fuji Electric", "Shreem Electric", "Eaton",
  "Luminous", "Microtek", "ABB", "Delta", "Larsen & Toubro", "Siemens",
  "Exide", "HPL", "Amaron", "Mitsubishi Electric", "Dell", "D-Link",
  "EPCOS", "Crompton Greaves", "Polycab",
];

export const clients = [
  "HNI India", "Metlok", "HCL", "Adani Power", "Mahavitaran", "WCL",
  "Indian Oil", "Kapilansh Dhatu Udyog", "Truform Engineers", "Mahagenco",
  "Johnson Lifts & Escalators", "Indian Ordnance Factory", "MMP Industries",
  "VNIT Nagpur", "PWD Maharashtra",
];

export const services = [
  { title: "Electrification & T/F Commissioning", description: "Total layout electrification with sanction from MSEDCL / Electrical Inspector Department." },
  { title: "Home Electrical & Lighting Supply", description: "Branded electrical material at higher discount than MRP." },
  { title: "MSEDCL Approved Energy Metering", description: "Sub-meters with connection co-ordination." },
  { title: "Street Light & Highmast", description: "End-to-end lighting installation for roads, grounds and townships." },
  { title: "Electrical Automation & Panels", description: "PLC, APFC, MCC, PCC and Industrial IoT panel building." },
  { title: "Comprehensive AMC & UPS Repair", description: "1-Phase & 3-Phase comprehensive AMC and on-site UPS repair." },
];
