import type { Category, Product } from "./types";

export const categories: Category[] = [
  { name: "Testing Equipment", slug: "testing-equipment", description: "Insulation testers, earth testers, megohmmeters and load test kits." },
  { name: "Measuring Instruments", slug: "measuring-instruments", description: "Multimeters, clamp meters, calibrators and oscilloscopes for site & lab." },
  { name: "Electrical", slug: "electrical", description: "Switches, MCBs, RCCBs, contactors, relays and general electrical accessories." },
  { name: "Power Tools", slug: "power-tools", description: "Drills, grinders, impact drivers and corded/cordless power tools for industrial use." },
  { name: "Hand Tools", slug: "hand-tools", description: "Pliers, screwdrivers, wrench sets, cable cutters and electrician hand tools." },
];

const img = (q: string) => `https://images.unsplash.com/${q}?auto=format&fit=crop&w=1000&q=80`;

export const products: Product[] = [
  // ─── Testing Equipment ───────────────────────────────────────────────
  {
    name: "Meco 6 PR Plus Insulation Tester 1000V",
    slug: "meco-6pr-plus-insulation-tester",
    description: "Hand-cranked insulation resistance tester for cables, motors and transformers. Wide test voltage range with auto-discharge.",
    category: "testing-equipment",
    brand: "Meco",
    price: 8500,
    mrp: 10500,
    stock: 18,
    images: [img("photo-1620714223084-8fcacc6dfd8d")],
    specs: { TestVoltage: "1000V DC", Range: "0–2000 MΩ", Display: "Analog", Warranty: "1 Year" },
    featured: true,
    tags: ["insulation tester", "megger", "1000v", "electrical safety"],
  },
  {
    name: "Kyoritsu 4105A Digital Earth Resistance Tester",
    slug: "kyoritsu-4105a-earth-tester",
    description: "3-pole earth resistance tester for grounding systems. Auto-ranging digital display, certified to IEC 61557-5.",
    category: "testing-equipment",
    brand: "Kyoritsu",
    price: 18999,
    stock: 7,
    images: [img("photo-1581094288338-2314dddb7ece")],
    specs: { Method: "3-Pole", Range: "0–2000 Ω", Standard: "IEC 61557-5", Warranty: "1 Year" },
    tags: ["earth tester", "grounding", "kyoritsu"],
  },
  {
    name: "HT Italia Combi 421-N Multifunction Installation Tester",
    slug: "ht-combi-421n-installation-tester",
    description: "All-in-one tester for electrical installations: insulation, continuity, earth, RCD, loop impedance and phase rotation.",
    category: "testing-equipment",
    brand: "HT Italia",
    price: 65000,
    stock: 3,
    images: [img("photo-1597852074816-d933c7d2b988")],
    specs: { Tests: "Insulation + Continuity + Earth + RCD + Loop", Memory: "999 results", Comms: "Bluetooth + USB" },
    tags: ["installation tester", "rcd", "loop", "ht italia"],
  },
  {
    name: "Motwane MFM 10kV Insulation Resistance Tester",
    slug: "motwane-mfm-10kv",
    description: "Heavy-duty motorised megger for HV testing of motors, generators and cables up to 10kV.",
    category: "testing-equipment",
    brand: "Motwane",
    price: 85000,
    stock: 2,
    images: [img("photo-1558494949-ef010cbdcc31")],
    specs: { TestVoltage: "10 kV DC", Range: "Up to 1 TΩ", PowerSource: "Motorised + Battery" },
    tags: ["megger", "hv test", "motwane", "10kv"],
  },

  // ─── Measuring Instruments ───────────────────────────────────────────
  {
    name: "Fluke 117 True-RMS Digital Multimeter",
    slug: "fluke-117-multimeter",
    description: "Electrician's everyday multimeter with True-RMS, non-contact voltage detection (VoltAlert) and low-impedance LoZ mode.",
    category: "measuring-instruments",
    brand: "Fluke",
    price: 15999,
    mrp: 18500,
    stock: 12,
    images: [img("photo-1620714223084-8fcacc6dfd8d")],
    specs: { Type: "True-RMS", VoltDC: "Up to 600V", VoltAlert: "Yes", Warranty: "Lifetime (Fluke)" },
    featured: true,
    tags: ["multimeter", "fluke", "true rms", "voltalert"],
  },
  {
    name: "Fluke 325 True-RMS 400A AC/DC Clamp Meter",
    slug: "fluke-325-clamp-meter",
    description: "Compact clamp meter with True-RMS, temperature & capacitance functions. CAT IV 300V / CAT III 600V rated.",
    category: "measuring-instruments",
    brand: "Fluke",
    price: 22500,
    stock: 8,
    images: [img("photo-1591488320449-011701bb6704")],
    specs: { ClampRange: "400A AC/DC", Type: "True-RMS", Rating: "CAT IV 300V / CAT III 600V" },
    tags: ["clamp meter", "fluke", "ac dc"],
  },
  {
    name: "Meco 603 Auto-Ranging Digital Multimeter",
    slug: "meco-603-multimeter",
    description: "Affordable everyday DMM for electricians and technicians — voltage, current, resistance, continuity and diode test.",
    category: "measuring-instruments",
    brand: "Meco",
    price: 2499,
    mrp: 2999,
    stock: 30,
    images: [img("photo-1581092580497-e0d23cbdf1dc")],
    specs: { Counts: "3 3/4 digit", VoltDC: "Up to 1000V", AutoRange: "Yes" },
    tags: ["multimeter", "meco", "digital"],
  },
  {
    name: "Rigol DS1054Z 4-Channel 50MHz Digital Oscilloscope",
    slug: "rigol-ds1054z",
    description: "Entry-level lab scope with 4 channels, 1 GSa/s sample rate and 24 Mpts memory depth.",
    category: "measuring-instruments",
    brand: "Rigol",
    price: 38500,
    stock: 4,
    images: [img("photo-1518709268805-4e9042af9f23")],
    specs: { Channels: "4", Bandwidth: "50 MHz", SampleRate: "1 GSa/s", Memory: "24 Mpts" },
    tags: ["oscilloscope", "rigol", "scope", "ds1054z"],
  },
  {
    name: "Kusam Meco LCR-Q Meter",
    slug: "kusam-meco-lcr-q",
    description: "Bench-top LCR meter for component R, L, C and Q-factor measurement.",
    category: "measuring-instruments",
    brand: "Kusam-Meco",
    price: 14500,
    stock: 6,
    images: [img("photo-1597852074816-d933c7d2b988")],
    specs: { Frequency: "100Hz–10kHz", Accuracy: "Class 0.5", Display: "LCD" },
    tags: ["lcr meter", "kusam meco", "q factor"],
  },

  // ─── Electrical ──────────────────────────────────────────────────────
  {
    name: "Schneider Acti 9 16A SP MCB C-Curve",
    slug: "schneider-acti9-16a-mcb",
    description: "Single-pole 16A miniature circuit breaker with C-curve characteristic. ISI-marked, suitable for lighting and small motor loads.",
    category: "electrical",
    brand: "Schneider Electric",
    price: 289,
    mrp: 350,
    stock: 120,
    images: [img("photo-1581094794329-c8112a89af12")],
    specs: { Rating: "16A", Poles: "1", Curve: "C", BreakingCapacity: "10 kA" },
    tags: ["mcb", "schneider", "16a", "circuit breaker"],
  },
  {
    name: "Havells Euro-II 32A 4P RCCB 30mA",
    slug: "havells-euro2-32a-rccb",
    description: "4-pole residual current circuit breaker with 30mA sensitivity for shock protection. ISI-marked.",
    category: "electrical",
    brand: "Havells",
    price: 3499,
    mrp: 4200,
    stock: 28,
    images: [img("photo-1597852074816-d933c7d2b988")],
    specs: { Rating: "32A", Poles: "4", Sensitivity: "30mA", Type: "AC" },
    featured: true,
    tags: ["rccb", "havells", "30ma", "shock protection"],
  },
  {
    name: "L&T MX1 9A 3-Pole AC Power Contactor",
    slug: "lt-mx1-9a-contactor",
    description: "9A 3-pole contactor with 230V coil. Suitable for motor starting up to 4kW.",
    category: "electrical",
    brand: "L&T",
    price: 1199,
    stock: 45,
    images: [img("photo-1565043589221-1a6fd9ae45c7")],
    specs: { Rating: "9A", Poles: "3", CoilVoltage: "230V AC", AC3: "Up to 4 kW" },
    tags: ["contactor", "l&t", "motor starter"],
  },
  {
    name: "Anchor Roma Classic 6-Module Box with Cover",
    slug: "anchor-roma-6m-box",
    description: "6-module modular GI metal box with white front cover. Pair with Roma Classic switches and sockets.",
    category: "electrical",
    brand: "Anchor",
    price: 699,
    stock: 80,
    images: [img("photo-1544197150-b99a580bb7a8")],
    specs: { Modules: "6", Material: "GI Metal + PC Cover", Finish: "White" },
    tags: ["modular box", "anchor", "roma", "switch plate"],
  },
  {
    name: "Polycab 4 sq.mm Heavy Duty Copper Cable Lug (10-Pack)",
    slug: "polycab-4sqmm-lug-10pack",
    description: "Tinned copper crimp-type cable lugs for 4 sq.mm cables. Sold in packs of 10.",
    category: "electrical",
    brand: "Polycab",
    price: 245,
    stock: 200,
    images: [img("photo-1581092918056-0c4c3acd3789")],
    specs: { CableSize: "4 sq.mm", Hole: "M6", Material: "Tinned Copper", Pack: "10 pcs" },
    tags: ["cable lug", "polycab", "copper", "crimp"],
  },

  // ─── Power Tools ─────────────────────────────────────────────────────
  {
    name: "Bosch GSB 550 13mm Impact Drill 550W",
    slug: "bosch-gsb-550",
    description: "Compact 550W impact drill with reversible switch and 13mm chuck. The classic site workhorse.",
    category: "power-tools",
    brand: "Bosch",
    price: 2899,
    mrp: 3499,
    stock: 22,
    images: [img("photo-1572981779307-38b8cabb2407")],
    specs: { Power: "550W", Chuck: "13mm", NoLoadSpeed: "0–2800 rpm", Reverse: "Yes" },
    featured: true,
    tags: ["drill", "bosch", "impact drill", "550w"],
  },
  {
    name: "Makita GA4530R 4-inch Angle Grinder 720W",
    slug: "makita-ga4530r",
    description: "Lightweight 4-inch angle grinder for cutting and grinding. Slim grip and anti-restart protection.",
    category: "power-tools",
    brand: "Makita",
    price: 3499,
    stock: 15,
    images: [img("photo-1530124566582-a618bc2615dc")],
    specs: { Power: "720W", DiscSize: "100mm (4\")", NoLoadSpeed: "11,000 rpm" },
    tags: ["angle grinder", "makita", "cutting"],
  },
  {
    name: "DeWalt DCD771 18V Cordless Drill Driver Kit",
    slug: "dewalt-dcd771-kit",
    description: "18V XR cordless drill driver with 2 batteries, fast charger and carrying case. Two-speed gearbox.",
    category: "power-tools",
    brand: "DeWalt",
    price: 14999,
    mrp: 17500,
    stock: 9,
    images: [img("photo-1572981779307-38b8cabb2407")],
    specs: { Voltage: "18V", Batteries: "2 × 1.5Ah", Speeds: "2", Chuck: "13mm Keyless" },
    tags: ["cordless drill", "dewalt", "18v", "xr"],
  },
  {
    name: "Bosch GBH 2-26 DRE SDS+ Rotary Hammer Drill",
    slug: "bosch-gbh-2-26-dre",
    description: "Professional 800W rotary hammer for SDS+ bits up to 26mm. Three modes: drill, hammer-drill, chiselling.",
    category: "power-tools",
    brand: "Bosch",
    price: 14250,
    stock: 6,
    images: [img("photo-1530124566582-a618bc2615dc")],
    specs: { Power: "800W", Capacity: "26mm in concrete", Modes: "3 (Drill/Hammer/Chisel)" },
    tags: ["hammer drill", "sds", "bosch", "rotary"],
  },

  // ─── Hand Tools ──────────────────────────────────────────────────────
  {
    name: "Taparia 1000V Insulated Combination Plier 210mm",
    slug: "taparia-1000v-combi-plier",
    description: "VDE-certified 1000V insulated combination plier with serrated jaws and side cutter. Made in India.",
    category: "hand-tools",
    brand: "Taparia",
    price: 699,
    stock: 60,
    images: [img("photo-1503423929435-d4ba43797bef")],
    specs: { Length: "210mm", Insulation: "1000V VDE", Standard: "IS/IEC 60900" },
    tags: ["plier", "taparia", "1000v", "vde"],
  },
  {
    name: "Stanley 38-pc 1/4\" Drive Socket Set with Bit Driver",
    slug: "stanley-38pc-socket-set",
    description: "38-piece 1/4\" drive metric socket set with ratchet handle, extension bars and bit driver. Hardcase included.",
    category: "hand-tools",
    brand: "Stanley",
    price: 2299,
    mrp: 2799,
    stock: 24,
    images: [img("photo-1503423929435-d4ba43797bef")],
    specs: { Pieces: "38", Drive: "1/4\"", Case: "Blow-mould Hardcase" },
    featured: true,
    tags: ["socket set", "stanley", "ratchet", "tool kit"],
  },
  {
    name: "Inder Heavy-Duty Manual Cable Cutter 38mm",
    slug: "inder-cable-cutter-38mm",
    description: "Manual ratchet cable cutter for copper and aluminium cables up to 38mm diameter (≤500 sq.mm).",
    category: "hand-tools",
    brand: "Inder",
    price: 1899,
    stock: 14,
    images: [img("photo-1581092918056-0c4c3acd3789")],
    specs: { Capacity: "Up to 38mm / 500 sq.mm", Cuts: "Cu + Al cables", Mechanism: "Ratchet" },
    tags: ["cable cutter", "inder", "ratchet", "cu al"],
  },
];

export const brands = [
  "APC", "Schneider Electric", "Fuji Electric", "Shreem Electric", "Eaton",
  "Luminous", "Microtek", "ABB", "Delta", "Larsen & Toubro", "Siemens",
  "Exide", "HPL", "Amaron", "Mitsubishi Electric", "Dell", "D-Link",
  "EPCOS", "Crompton Greaves", "Polycab",
];

export const clients = [
  "HNI India", "Metlok", "HCL", "Adani Power", "Mahavitaran", "WCL",
  "Indian Oil", "Kapilansh Dhatu Udyog", "Truform Engineers", "Mahagenco",
  "Johnson Lifts & Escalators", "Indian Ordnance Factory", "MMP Industries",
  "VNIT Nagpur", "PWD Maharashtra",
];

export const services = [
  { title: "Electrification & T/F Commissioning", description: "Total layout electrification with sanction from MSEDCL / Electrical Inspector Department." },
  { title: "Home Electrical & Lighting Supply", description: "Branded electrical material at higher discount than MRP." },
  { title: "MSEDCL Approved Energy Metering", description: "Sub-meters with connection co-ordination." },
  { title: "Street Light & Highmast", description: "End-to-end lighting installation for roads, grounds and townships." },
  { title: "Electrical Automation & Panels", description: "PLC, APFC, MCC, PCC and Industrial IoT panel building." },
  { title: "Comprehensive AMC & UPS Repair", description: "1-Phase & 3-Phase comprehensive AMC and on-site UPS repair." },
];
